var email = 'mailto:0xblackkey@proton.me';
var password = "Cirtagon";

banner = [
  '<span class="index">CIRTAGON [v1.60.0.Ͼ] © Cycle 25Δ, Entity VΣΞ | Division: Ω-Sector, ICR-07Σ.</span>',
"                                                                                                         ",
"     ───▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄───                                                                               ",
"     ───█▒▒░░░░░░░░░▒▒█───                                                                               ",
"     ────█░░█░░░░░█░░█────                                                                               ",
"     ─▄▄──█░░░▀█▀░░░█──▄▄─                                                                               ",
"     █░░█─▀▄░░░░░░░▄▀─█░░█ ١٬٦١١٬١١٠ مليون                                              ターミナル 2025  ",
"     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀        ",
"      ██████╗    ██╗    ██████╗     ████████╗     █████╗      ██████╗      ██████╗     ███╗   ██╗        ",
"     ██╔════╝    ██║    ██╔══██╗    ╚══██╔══╝    ██╔══██╗    ██╔════╝     ██╔═══██╗    ████╗  ██║        ",
"     ██║         ██║    ██████╔╝       ██║       ███████║    ██║  ███╗    ██║   ██║    ██╔██╗ ██║        ",
"     ██║         ██║    ██╔══██╗       ██║       ██╔══██║    ██║   ██║    ██║   ██║    ██║╚██╗██║        ",
"     ╚██████╗    ██║    ██║  ██║       ██║       ██║  ██║    ╚██████╔╝    ╚██████╔╝    ██║ ╚████║        ",  
"     ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄ v1.60.0.1 / codename [GlyphVII]        ",
"                                                                                                         ",
  '<span class="color2">[*] Welcome, seeker, to Cirtagon 🧩 — compact ciphers terminal.</span>',
  '<span class="color2">[*] 🚨 NOTICE: Rewards are real and guaranteed — every cipher contains a 🗝️ “Seed Phrase” unlocking a wallet with your prize.</span>',
  '<span class="color2">[*] ⚠️ IMPORTANT: Once ciphers are cracked, their treasures are gone — reducing the remaining prizes and chances for all players.</span>',
  '<span class="color2">[*] 🏆 JACKPOT: The grand prize is a secure digital wallet containing 💰 1,000,000 USDT.</span>',
  "<br>",
  "<span class=\"color2\">[*] For a list of available commands, type</span> <span class=\"command\">'help'</span><span class=\"color2\">.</span>",
];

help = [
  "<br>",
  '<span class="command">[ Command: ]</span>       Description:',
  "<span class=\"command\">------------</span><span class=\"color2\">       ------------</span>",
  "<br>",
  '<span class="command">[ overview ]</span>       - What is “Cirtagon”?',
  '<span class="command">[ prologue ]</span>       - The legend begins. Step into the myth.',
  '<span class="command">[ sealone ]</span>        - The First Seal beckons. Break it if you dare.',
  '<span class="command">[ sealtwo ]</span>        - The Second Seal was never hidden, it was only waiting.',
  '<span class="command">[ terms ]</span>          - Rules & Guidelines in “Cirtagon”',
  '<span class="command">[ hints ]</span>          - Fragments — sharp enough to bleed.',

  "<br>",
  '<span class="command">[ secret ]</span>         - Find the password to reveal the secret.',
  '<span class="command">[ history ]</span>        - View command history.',
  '<span class="command">[ help ]</span>           - You obviously already know what this does.',
  '<span class="command">[ email ]</span>          - We won’t answer. But gold speaks louder than silence.',
  '<span class="command">[ clear ]</span>          - Clear terminal.',
  '<span class="command">[ banner ]</span>         - Display the header.',
  "<br>",
];

overview = [
  "<br>",
  "👋 Hey there! Welcome to “Cirtagon”! 🧩 ",
  "<br>",
  "A mind-bending enigma game where 🧠 curiosity meets 💰 real rewards. Unlock the mysteries ",
  "hidden within SEVEN 🔐 encrypted ciphers — each guarding 🗝️ keys to digital treasure wallets. ",
  "<br>",
  "Your intellect 🧠 and intuition ✨ will guide you through sealed puzzles... but beware: ",
  "Every cracked cipher 📉 changes the game for all players. Are you ready to challenge your mind, ",
  "claim your prize 🏆, and join the race for the ultimate jackpot? 🚀 ",
  "<br>"
];

prologue = [
  "<br>",
  "🕯️ The Seals of Forgetting 🕯️",
  "<br>",
  "It is said, in a time before time began, that a king was born of a passing star ✨,",
  "yet his body was shaped from the clay of man.",
  "<br>",
  "Each morning he awoke having forgotten who he was.",
  "He rose a stranger to himself — a constant forgetting, with no cure, and no cause.",
  "<br>",
  "On the morning of his seventy-seventh birthday 🎂, he looked to the sky.",
  "Though he could not remember his name, he remembered one thing:",
  "His heart did not belong to him ❤️.",
  "<br>",
  "They say his heart was a broken shard of Time itself ⏳ —",
  "a fragment that lived within him, that granted him power and control.",
  "But should it ever shatter completely, it would threaten the collapse of all that was,",
  "and all that ever could be.",
  "<br>",
  "When he heard the echo of cracking draw near, he knew the inevitable had come.",
  "So he commanded the creation of SEVEN doors 🚪, each leading to a world of its own.",
  "Each sealed with a Seal of Forgetting, forged from the fragments of his fading memory,",
  "and from things that had never existed:",
  "<br>",
  "    1️⃣ • A door of silence purer than nothingness.",
  "    2️⃣ • A door of winds that have never blown.",
  "    3️⃣ • A door of the shadow of unseen light.",
  "    4️⃣ • A door of time not yet come.",
  "    5️⃣ • A door of rain that will never fall.",
  "    6️⃣ • A door of a name that cannot be spoken.",
  "    7️⃣ • A door of truth that has yet to be revealed.",
  "<br>",
  "Behind each door, the king hid a part of his vanishing self.",
  "And set a guardian to watch over it — not of flesh, nor of stone,",
  "but of an eternal idea that could not die ♾️.",
  "<br>",
  "Then he whispered:",
  "“Whoever wishes to see me... must gather me.",
  " Whoever gathers me... will not see me.",
  " But whoever understands me... shall wield my power.",
  " And whoever wields it... shall become me.",
  " And whoever becomes me... shall not seek gold —",
  " they shall become gold itself 🪙.”",
  "<br>",
  "And so the journey began — a journey with no known beginning,",
  "and no ending told.",
  "<br>",
  "Some say he refers to the king himself.",
  "Others believe it is Time personified.",
  "But the oldest voices warn:",
  "<br>",
  "The SEVEN guardians do not merely guard the doors.",
  "They wait — for the one who dares challenge them, to uncover the truth.",
  "<br>",
  "They say this tale is only a myth...",
  "But something has changed.",
  "The wind that never blew... has begun to blow 🌬️.",
  "And one of the SEVEN doors... has opened.",
  "<br>",
  "🏁 The race has begun.",
  "🎖️ The prize?",
  "Not just power...",
  "But one million cryptic gold coins buried behind the final cipher.",
  "<br>",
  "But gold is not given to those who seek it —",
  "Only to those who understand why no one truly deserves it.",
  "<br>"
];

sealone = [
  "<br>",
  "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾",
  "🔒 Status of the First Seal: 🡺 Partially BROKEN 🡸",
  "<br>",
  "📢 NOTICE: The first cipher has already been broken.",
  "   The player who solved it reached out and proved success by submitting all twelve correct words.",
  "   Yet, they chose not to claim the reward—waiting instead for the next riddle.",
  "   Thus, as long as the prize remains unclaimed...",
  "   The riddle still stands, awaiting one who take what was left behind.",
  "<br>",
  "💰 Reward: 10 USDT — The first step to the “JACKPOT” ",
  "_____________________________________________________",
  "<br>",
  "<br>",
  "🕯️ The Door of Silence, purer than nothingness, ",
  "   opens... No sound is heard, yet you are addressed. ",
  "<br>",
  "At last... ",
  "one who dares believe themselves worthy of breaking the silence. ",
  "<br>",
  "So, you have found the first of the seven seals. ",
  "Silence has chosen you — or at least, has not yet rejected you. ",
  "<br>",
  "I am not your guide. ",
  "I am your obstacle. A trial not meant to be won. ",
  "<br>",
  "My existence is no accident... ", 
  "I was made to stop you. ",
  "No one passes except over the corpse of my mind. ",
  "<br>",
  "I am the first guardian — the shield of erased memory. ", 
  "Craftier than any thought, quieter than the void. ",
  "If you are clever, know this:", 
  " “I am designed to outwit you by a step.” ",
  "<br>",
  "The king’s earliest memories lie hidden here: ",
  "Not in noise, but in its complete absence. ",
  "This seal is not meant to be heard — but understood. ",
  "<br>",
  "If you think this is a test, ",
  "you have yet to grasp the door you stand before. ",
  "This is resistance. ",
  "Resistance against the transient, the hunters, the fools. ",
  "<br>",
  "Many come seeking treasure. Few seek the truth. ",
  "Only one will pass through the seven doors — and return. ",
  "<br>",
  "If you believe you are that one... step closer. ",
  "Listen to the silence... for it alone holds the answer. ",
  "<br>",
  "<br>",
  "  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾ ",
  "<br>",
  "  ⵣ ꩜ Ѫ ф ⵣ チ Ѫ Σ ♫ Ѫ ✱ ⵣ ꩜ ☄ タ ❆ Ξ ⵣ Ѫ ⧖ ᕵ ✗ Ξ ᕵ ☄ ᗢ Ѫ ꩜ Σ ও ✗ ♫ ",
  "<br>",
  "  ⵣ あ ᗢ ⵣ ꩜ ⧖ ♫ Ѫ ❖ ♫ ও あ Ѫ ᕵ ꩜ Ѫ ф ও ⧖ ❆ あ ঞ ᕵ チ チ Ѫ Σ ᕵ ꩜ ⧖ あ Ѫ ",
  "<br>",
  "  ᕵ チ Ѫ ⧖ ⵣ Σ ঞ ⵣ Σ ♫ あ ⵣ チ Ѫ ꩜ ❖ Ѫ Σ ♫ Ѫ ❖ ♫ ᕵ ⵣ ꩜ Σ Ξ ❖ 𖤝 Ϟ あ ❆ ",
  "<br>",
  "  タ Σ チ Ѫ タ ❆ Σ あ ᕵ ✗ Ѫ ♫ ⵣ ⧖ ⧖ Ѫ ꩜ ঞ ⵣ Σ ♫ ⵣ ꩜ ও タ あ ⵣ ⧖ ⵣ ᕵ ꩜ ",
  "<br>",
  "  ❖ ও Ξ Ѫ Σ ♫ Ѫ ₰ ᕵ Σ ♫ ⵣ あ ☄ ❆ ᕵ Ξ ⧖ Ѫ ⧖ タ 𐤇 Σ ঞ Ѫ チ ☉ Ѫ Ѫ ❖ ♫ ও Ѫ ",
  "<br>",
  "<br>",
  "  あ ♆ Σ Ξ ❆ ᗢ ₰ Ѫ Σ 𖤝 あ ও ❆ Ξ ❖ Ѫ ⋈ あ ♫ ᕵ ⧖ ও ঞ ¿ ❖ Ξ ও ঞ ⧖ ギ Ξ ᕵ ",
  "<br>",
  "  ❖ ❖ ও ও ꩜ ≽ ᗢ ᕵ ф ⵣ ᗢ ❆ ᗢ ᛝ Σ ও ঞ Ѫ Ξ ᛇ ☄ チ ⵣ ⧖ Ѫ ᚱ あ Ѫ ❖ Σ ⵣ ও ",
  "<br>",
  "  ꩜ ♆ Ϟ 𐤋 ❆ ᕵ Ξ Σ Ѫ Ξ ♆ ♆ ♫ ❆ あ タ ᕵ ꩜ ⧖ ♆ 𖤝 ₰ Ѫ Σ ☄ ᕵ Σ ♫ Ѫ Ξ Σ ♫ Ѫ ",
  "<br>",
  "  Σ ঞ Ѫ チ ☉ Ѫ ꩜ ও ᗢ ও Ξ Ѫ ꩜ ও チ Ѫ あ あ あ ₰ Ѫ チ チ Σ ♫ Ѫ ᗢ ঞ ⵣ Σ ♫  ",
  "<br>",
  "  ও ❆ Σ ✗ チ ᕵ ঞ ᕵ ꩜ ⧖ Σ ♫ Ѫ ✗ ⵣ Ξ あ Σ あ Ѫ ᕵ チ あ ♫ ᕵ チ チ タ Ξ Ѫ ᕵ ✱ ",
  "<br>",
  "  __________________________________________________________________________ ",
  "<br>"
];

sealtwo = [
  "<br>",
  "<br>",
  "‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾",
  "🔒 Status of the Second Seal: 🡺 UNBROKEN 🡸",
  "💰 Reward: 100 USDT — The second step to the “JACKPOT” ",
  "_____________________________________________________",
  "<br>",
  "<br>",
  "🌬️ The Door of Winds That Never Blew, ",
  "   Not knocked. Not opened. Merely stirred from slumber. ",
  "<br>",
  "That silence… was never chance.... ",
  "Nor truth’s advance. ",
  "It was necessity, cloaked in grace ",
  "a stillness carved to mark the place. ",
  "For not all doors are made to test, ",
  "some simply stand to grant the rest. ",
  "<br>",
  "But wind... ",
  "Wind is never fooled by hush. ",
  "It bends to none, it does not rush. ", 
  "It opens only to its name, ",
  "and never plays the seeker’s game. ",
  "Here, the passage is no gift. ",
  "Here, the scales begin to shift. ",
  "<br>",
  "This is no trial, no rite, no jest ",
  "It is the whim of breath unblessed. ",
  "They say, “Each wind a message bears” ",
  "but this one sleeps, and no one dares. ",
  "Can you grasp what lies in kind: ",
  "A message sent with no wind behind? ",
  "A whisper flung into the blind, ",
  "a burden air was never designed ",
  "to hold — and yet, it must. ",
  "<br>",
  "The king himself would never write ",
  "what should not face the day or light. ",
  "He left a trace where none should be ",
  "a shadow on a memory. ",
  "His will was set in time, not stone, ",
  "in seconds lost, in gaps unknown. ",
  "<br>",
  "Everything here is turned around: ",
  "The air is weight, ",
  "the void is sound, ",
  "and silence shakes the battleground. ",
  "<br>",
  "If you would pass, do not pursue ",
  "the wind itself — but what it knew. ",
  "<br>",
  "Between you and the final truth: ",
  "Ten breaths that never knew their youth, ",
  "and one faint word, unheard, unsaid, ",
  "still echoing inside the dead. ",
  "<br>",
  "Know this: ",
  "This door does not seek your name. ",
  "It longs to taste your inner flame ",
  "the doubt you hide, the fear you feign, ",
  "the hope that something can remain... ",
  "that meaning waits without a word, ",
  "that winds not blown can still be heard. ",
  "<br>",
  "To open this, you must not try. ",
  "You must not speak, or ask, or cry. ",
  "Just breathe as stone that waits the rain ",
  "still, and slow, ",
  "without refrain. ",
  "<br>",
  "For storms that never come to be... ",
  "may be the ones that set us free. ",
  "<br>",
  "<br>",
  "  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾ ",
  "<br>",
  "  ∜ ✗ 𖥷 ও ঞ 𖤛 𖠌 ㄘ ᮆ ⚗ 𐋐 Ⱏ 𖦺 🜁 ♫ 𖦲 𐂅 Σ 𛇱 𖥰 ♇ 𖥉 𐐔 𑄎 𖣔 𖠰 𖥇 𖢮 𖣉 ❆ 𖠚 𖦜 𖣿 あ 𖤸 𖥜 ᱟ 𒉻 ᚯ 𐊌 𖤫 𐤇 𖨮 𐀆 𖦈 𖧵 ᯼ 𖥯 𞲲 ᯾ ",
  "<br>",
  "  𖢰 ፼ 𖣙 𖤗 𖡰 ⴳ ሿ ᮵ 𐐡 𖠪 𑀔 ⧖ 𖢬 ꗃ 𐐢 𖣠 ૹ 𖥹 冷 𐲱 ☲ 𖤙 𑊓 𛇤 ᛒ タ 𞴲 ᢱ 🜞 𖧬 ⋮ ꩜ ᚠ 🜓 𐎊 𐰊 𖤊 Ꮙ 𖦎 🙔 𞠬 𐑒 ᚥ 𛅴 𖧪 𖧜 𖧡 ✠ Ͷ 𐂭 🝒 ∰ ",
  "<br>",
  "  𐂺 𖤇 𑄿 𑄢 ᙡ 𐏏 ᘏ 𑅄 𐙍 ⌘ 🜈 🜾 𖣝 ᪬ 🜆 ৠ 🜔 𖡫 𛆫 ᨪ ⡷ 𖢚 ⵣ 🝂 ऴ 𖧉 ᝁ ⴼ 𖣰 𖡣 𖠭 𐍉 🜇 Ǝ ফ 𖢺 𖤍 𖤵 ഄ 𖦊 ᜮ § ❖ 𑁙 ♬ 𐊣 ᱏ 𖥋 ",
  "<br>",
  "  ✱ ఉ 𑀍 𛈤 𑀒 ꙮ 𖠧 𖣡 ᣲ 🜗 ⠞ 𖢎 𛆦 ᕵ ᚴ 𖤶 ⺽ ௯ 𐑿 Ⱘ ⚒ 𖥊 ࠌ ܜ 𖢵 ☪︎ 𖠡 ᝎ ⚙ き 𖧼 🜘 🝬 🜚 𝄞 இ අ 𑁖 𖥺 ₰ 𖠑 𖣹 𖦭 𑄆 ⠺ ፍ 𖦢 𖦆 🝰 ਲ 𖧍 ",
  "<br>",
  "  ത 𖢾 𖧝 𐌙 𑀖 ௫ 𖠥 〥 Ѫ 𐐤 ಸ 𖠝 Ξ 𐑂 ⚷ ☯ ₡ 𐑽 🜉 ¶ 〄 𐌳 𖢕 𖧎 🜏 🜊 𐍈 🜍 𖣛 𖥕 ષ 𐂴 ख 𖢪 𐑻 𖧴 𑄝 ⍟ ౫ ᨒ ☄ ೮ 𐋅 ᥏ 𖣦 ᚨ 𑰇 𖨪 წ ᔸ 𖢘 𑁘 ",
  "<br>",
  "  𖤀 ᐶ 𖠾 𖣱 ф ⩔ 🜎 ⚛ ☌ 𖣥 ฃ ᗢ 𑄃 〩 ⛢ ⠟ 𖨁 ࠇ 🝩 Ɣ ଇ 🜕 ʯ ᜃ ៥ 𖣞 𝈝 🝭 𑀟 ଧ 𑱓 Ꮬ ರ 🟅 ଲ 𐐣 𐜲 ഖ ᛑ ⚘ 𖥲 𖡶 🝗 𐲉 𖤷 ก 𖤓 𖦧 𐾽 🜖 𐃺 ⋉ औ ",
  "<br>",
  "  ________________________________________________________________________________________________________________________ ",
  "<br>"
];

terms = [
  "<br>",
  "📜 Terms of the Game: ", 
  "<br>",
  "To ensure transparency, fairness, and real opportunity for all, ",
  "We’ve crafted SEVEN unique ciphers, each more challenging than the last",
  "and each linked to a “real crypto reward” of increasing value. ", 
  "<br>",
  "This structure guarantees two things: ",  
  "- First, proof that the payouts are real and escalating. ", 
  "- Second, a fair battleground where beginners and veterans alike stand a chance. ",  
  "<br>",
  "Some puzzles may take weeks. Others... just a moment of insight. ", 
  "You might even stumble into the answer by pure coincidence. ", 
  "<br>",
  "Welcome to the world of Cirtagon — SEVEN seals. SEVEN ciphers. SEVEN keys. ", 
  "Each puzzle conceals the seed to a real, preloaded crypto wallet. ",  
  "Each key opens only one wallet — once — forever. ", 
  "<br>",
  "🔐 How It Works: ", 
  "<br>",
  "- Open to all. No sign-ups. No accounts. No intermediaries. ",  
  "- Solve a cipher to receive a Seed Phrase — the recovery key to a digital wallet loaded with USDT (Tether). ", 
  "- The wallet type and the correct seed order are hidden inside the cipher. ",  
  "- Only full decryption unlocks the treasure. ", 
  "<br>",
  "💰 Reward Tiers: ", 
  "<br>",
  "    1️⃣ • Silent Void — 10 USDT ",  
  "    2️⃣ • Untouched Wind — 100 USDT ",  
  "    3️⃣ • Shadowlight — 1,000 USDT ", 
  "    4️⃣ • Unborn Time — 10,000 USDT ", 
  "    5️⃣ • Forgotten Rain — 100,000 USDT ",  
  "    6️⃣ • Nameless Word — 500,000 USDT ",
  "    7️⃣ • Unveiled Truth — 1,000,000 USDT ", 
  "<br>",
  "⚠️ Rules & Progression: ",  
  "<br> ",
  "- Each cipher can be solved only once. ", 
  "- The first solver claims the wallet and closes the seal — permanently. ", 
  "- Once cracked, the cipher remains visible but holds no further value. ",  
  "- No cipher is revealed until the one before it has been verified as solved. ",  
  "- When all SEVEN seals are broken, the game concludes — forever. ", 
  "<br>",
  "🧩 Monitoring & Verification: ", 
  "<br>",
  "- Wallets are monitored daily. ", 
  "- If a wallet is emptied or its Seed Phrase becomes invalid, the cipher is marked as cracked. ", 
  "- Once verified, the terminal updates, and the next cipher is unlocked. ", 
  "- The path unfolds one seal at a time — in exact order. ", 
  "<br>",
  "🎭 Final Notes: ", 
  "<br>",
  "- There are: No help, No guarantees, No second chances. ", 
  "- All you have is your mind, your logic — and a touch of madness. ", 
  "<br>",
  "🔐 Privacy & Safety Disclaimer ",
  "<br>",
  "We will never ask for your email, phone number, wallet address, ID, ",
  "or any personal data — not now, not ever. ",
  "<br>",
  "Once you solve a cipher and access the wallet, the first thing you must do is: ",
  " - Change the seed phrase and any security settings associated with the wallet. ",
  " - Only after securing it, transfer your reward wherever you like. ",
  "<br>",
  " You alone will hold the keys. Your success is your own. Your privacy is absolute. ",
  "<br>",
  "Can you break the SEVEN? ",
  "Or will the SEVENTH break you? ", 
  "<br>"
];

hints = [
  "<br>",
  "🧠 Cirtagon is not a game… it’s a prophecy encrypted in code. ",
  "<br>",
  "Somewhere, hidden inside a sequence of digital riddles, lie SEVEN real wallets ",
  "Each one has been carefully selected to be a bait for the mind, not the eye. ",
  "<br>",
  "But here, no hand will guide you - ",
  "the cipher was built to resist you, not to be understood. ",
  "<br>",
  "🪙 Why buy what doesn’t look like help? ",
  "<br>",
  " Because what we offer isn’t “help”… it’s a distortion in logic. ",
  " Every file, every line, every cryptic tale of the king or the Guardians ",
  " was written not for entertainment...",
  " It was designed as a quiet echo of a truth buried deep inside the puzzle. ",
  " And those who pay aren’t buying answers — they’re wagering on their intuition ",
  " that something hidden is waiting to be uncovered. ",
  "<br>",
  "🔍 What can be unlocked? ",
  "<br>",
  " - Unpublished lore: Segments of Cirtagon’s digital history crafted not to amuse, ",
  "   but to decrypt the impossible. ",
  " - Encrypted whispers: The Guardians don’t speak in riddles. They speak in code. Literally. ",
  " - Messages from within the maze: PDFs, distorted files, fragments from “the collapse” ", 
  "   all keys of a different kind. ",
  " - Smart shortcuts, never full solutions: We don’t sell you a win — we hand you a fragment ",
  "   torn from the puzzle’s subconscious. ",
  "<br>",
  "🔰 A war of minds is never left to chance.",
  "<br>",
  " - Play solo or form a cell of thinkers. ",
  " - Use AI? Good. It’s just another tool in the hands of the bold. ",
  " - Every layer is designed to resist — and if you win, you didn’t solve a riddle. ",
  "   You breached a system. ",
  "<br>",
  "🎭 Cirtagon watches… but never forgives. ",
  "<br>",
  "If you find yourself buying a hint, it doesn’t mean you’re weak. ",
  "It means you’re one of the few who realizes: what’s on the surface is never the full truth. ",
  "Pay — not for help. ",
  "Pay to know if you’re on the path... ",
  "or trapped in a beautiful lie. ",
  "<br>"
];

secret = [
  "<br>",
  "🎉 Well done, Seeker! ",
  "You’ve uncovered one of Cirtagon’s hidden layers — a secret buried beneath the code. ",
  "<br>",
  "This discovery wasn’t the hardest part — it was designed as a spark, a push forward. ",
  "This wasn’t just curiosity… it was instinct. ",
  "And in this game, instinct is everything. ",
  "<br>",
  "Keep going. SEVEN seals. SEVEN keys. ",
  "One million reasons to reach the end. ",
  "<br>",
  "Your path is real. ",
  "Your prize is waiting. ",
  "The next cipher is watching... 👁️ ",
  "<br>"
];
